### ISSUE TITLE
Buzz still needs to be properly integrated

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#10]

**Comment by ppyordanov** [comment]
still trying different approaches on synchronizing overlapping files

**Comment by kaffo** [comment]
Guys who've been dealing with this. Have we _ever_ had buzz play two sounds at once? Is it a legit thing? If not then we need to stop dicking about with it and sort out a new library.

**Comment by allyjweir** [comment]
buzz demo folder has one playing 3 files at once that I made

**Comment by ppyordanov** [comment]
It works of course Ally has set up a demo. However, grouping files starts them at the same time, thats the issue (ovderlapping recordings starting at different times will be a situation that I dont see how buzz.group().play() is going to deal with). So we need to create separate sound objects rather than group them and save their filepaths + start times in a data structure as I mentioned. Then iterate over it and set up the objects + buzz.play() on the separate instances. However, This will make it difficult to pause all instances if we need more control cause we will need to keep track of which files are playing at any given moment.

Here is the buzz library: http://buzz.jaysalvat.com/documentation/buzz/

If you think of other approaches, shout!

**Comment by kaffo** [comment]
Is it a legit method to group all the sounds that should be playing at the current time, then increment each sound to where it's supposed to be using .setTime(currenttime - soundstarttime) then play them all from those positons?

**Comment by ppyordanov** [comment]
It is a legit method within the file replay itself - you could set the file to play from 50% the length, 1 minute, etc. But I have not discovered a way to increment start times in relation to multiple sound instances.

**Comment by allyjweir** [comment]
This still hasn't been sorted...

**Comment by ppyordanov** [comment]
I'm having all sorts of trouble with synchronous/ asynchronous javascript but essentially this script will work.

**Comment by ppyordanov** [comment]
PS: Once I fix the asynchronous get requests.

**Comment by ppyordanov** [comment]
Just a quick comment to avoid confusion - it works I tested it with overlapping files.
