### ISSUE TITLE
No menu on mobile devices

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#18]
One of @gtadam 's recent commit hides the menu completely on a mobile browser or if you resize your page on a desktop

**Comment by calxus** [comment]
Trying to get this to work properly is somewhat infuriating. If anyone can get this working i'll buy them a beer.

**Comment by ppyordanov** [comment]
Now the menu is hidden only if the page with is so small that the map cannot be seen at all for convenience purposes.

I left it at 300 px just to be on the safe side after a quick mobile display size research (turns out that the smallest displays/ resolution density or dpi out there is around 320 px):

http://www.binvisions.com/articles/tablet-smartphone-resolutions-screen-size-list/
