### ISSUE TITLE
Acknowledgement of selection of recording

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#31]
We should acknowledge with a little pop up (something jQuery probably does) or something that acknowledges that you have selected or cleared all the recordings in an area. Similar to the tweet sent thing on twitter.com
![screenshot 2014-02-17 12 47 28](https://f.cloud.github.com/assets/3640069/2185252/bc2eda14-97d1-11e3-82e3-7a718582dbdf.png)

There should be a visual indication as well. We could add a red outline to the current marker to show which ones are selected.

**Comment by calxus** [comment]
To show which ones are selected, the visual indication with the red outline is doable. However the popup could just end up being more hassle than it's worth in the end. 
Is this something that is really needed?
The acknowledgement that it is selected could be just the red indication and the info window that opens.

**Comment by allyjweir** [comment]
nah, the marker change should do. doing the pop up is jQuery. we could always come back to it if we figure it out better with DIM3.

the markers are fine on their own

**Comment by calxus** [comment]
I have implemented the colour changing when the marker is clicked to represent the fact that it is selected.

Right now clicking the close on the info window de-selects it. 

However I would like to change this to clicking the marker again in order to de-select it. and just keep the info window separate.

The info window would open when the marker is selected by a click on it and would only close if it is closed directly.

The "select all" and "de-select all" buttons on the menu would neither open nor close the info window.
