### ISSUE TITLE
Implement Selection Properly

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#33]
The icon for reasons unbeknown to me, fails to change to selected about 20% of the time

**Comment by calxus** [comment]
The icon will now change each time, however, when you pan the map it changes back to de-selected.

**Comment by calxus** [comment]
Also whether the icon chooses to be selected or not, appears to depend largely on it's mood. Good news however is that when it feels like being selected, it tends to keep working after that.

**Comment by kaffo** [comment]
From just reading this (I obviously don't know the issue indepth) I've got to assume it's because you are pulling new data every single time the map is moved or anything happens, so even though the data may be identical, it's a fresh set and it's no longer selected? In anycase, considering how completely horribly we are doing the pull from the backend (but it works!) we might just have to deal with this issue right now....

**Comment by calxus** [comment]
Yes you are right with this, speak about it at the meeting.

**Comment by calxus** [comment]
Got this almost working, the only problem is when markers are removed from view in the map. which tends to cause erratic behaviour. I'm going to try and get this hammered down tonight and avoid sleep.

**Comment by calxus** [comment]
After spending way too long on it, I've managed to get this functional at least to my testing. If any bugs are found just raise an issue.
