### ISSUE TITLE
Get the crazy timeline actually functional

### ISSUE THREAD

**Issue by kaffo** [kaffo/multi-device-audio-project#7]
It's pretty. Now make it actually work

**Comment by allyjweir** [comment]
working on a prototype pulling data from a json file

**Comment by allyjweir** [comment]
see notes from commit

**Comment by allyjweir** [comment]
Using this will be able to generate JSON from the db. Will work on this tonight.

http://www.anthonydebarros.com/2012/03/11/generate-json-from-sql-using-python/

**Comment by allyjweir** [comment]
of course django already has a function for that https://docs.djangoproject.com/en/1.6/topics/serialization/

**Comment by ppyordanov** [comment]
I've been banging my head whole night trying to use custom natural keys when serializing the data in order to save it in a format compatible with the timebar. So far no much progress but will keep trying. Basically the fields in the Recordings table in the database should have specifically defined nat. keys for the timeline to be able to read the json. If you have any other ideas comment.

**Comment by ppyordanov** [comment]
Helpful post, suggests designing a template: http://stackoverflow.com/questions/3055650/django-custom-serialization-options

**Comment by ppyordanov** [comment]
Also, Keir has already added serialization functions in views.py, However, timeline does not accept this structure.

**Comment by ppyordanov** [comment]
I contacted the creator of the timeline to ask for some advice on how to customize the serialization process of JSON. Here is the reply:

---

Peter:

Are you asking for information about how to structure the JSON? The best documentation for that is at https://github.com/NUKnightLab/TimelineJS ; our examples http://timeline.knightlab.com/examples/houston/ and http://timeline.knightlab.com/examples/user-interface/ are also driven by JSON, so you could inspect the source of them to find the JSON and look at real examples.

Otherwise, it’s just a matter of mapping your model data into the TimelineJS data structure, and either rendering the JSON in an HTML template or (what I’d probably choose) setting up another mapping in your Django urls.py that goes to a url that simply returns the JSON as if it were a file.

I hope this helps.

Joe

## 

Joe Germuska • joegermuska@northwestern.edu • @JoeGermuska
Chief Nerd, Knight Lab • http://KnightLab.Northwestern.edu • @KnightLab

---

So an HTML template is probably the best way to approach this.

**Comment by ppyordanov** [comment]
The timeline JSON script generation function is ready. Now we need to fill the database with mock data and test.

**Comment by allyjweir** [comment]
In sure you could script that too

**Comment by ppyordanov** [comment]
yes im working on it and fixing bugs should test it by tomorrow evening

**Comment by JoeGermuska** [comment]
Btw, I am not the creator of Timeline. That would be Zach Wise. I am just currently managing it's maintenance.

**Comment by ppyordanov** [comment]
Now it is working and I have tested it with mock information. There are still things to be changed but now it successfully queries the database and visualizes the information on the front end:
- start/ end time of the recording as well as the duration
- name
- event association (should tweak it further)
- description
- images displayed
- map location displayed

**Comment by ppyordanov** [comment]
OK so this is how it is looking. I am going to embed the music player with the recordings on the right and on the left will appear images/ map location.

https://www.dropbox.com/s/bd3wrkopq4wf8lo/timeline.png
